apiVersion: v2
name: longhorn
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.2.0"
dependencies:
  - name: longhorn
    version: 1.2.4
    repository: https://charts.longhorn.io