ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

s3Secret:
  name: s3-secret
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_ENDPOINTS: AWS_ENDPOINTS
  AWS_REGION: AWS_REGION
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY

httpBasicAuth:
  name: http-basic-auth
  httpBasicAuth: auth

longhorn:
  persistence:
    defaultClassReplicaCount: 1
  defaultSettings:
    backupTarget: 's3://bucket@region/longhorn'
    backupTargetCredentialSecret: 's3-secret'
    defaultLonghornStaticStorageClass: 'longhorn'