---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid.fullname" . }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
data:
  squid: {{ .Values.squidConf | toYaml | indent 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "squid.fullname" . }}-auth"
  labels:
    {{- include "squid.labels" . | nindent 4 }}
data:
  squid: {{ .Values.authConf | toYaml | indent 1 }}
---