{{- if .Values.persistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: "{{ .Values.persistentVolumeClaim.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolumeClaim.amount | default "100Mi" }}"
{{- end }}