apiVersion: v2
description: Crypto Port Fiat Helm chart for Kubernetes
name: fiat
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.16.0-0"
keywords:
  - crypto-port
  - crypto-port-fiat
  - fiat
home: https://github.com/Zekihan/helmcharts/tree/main/crypto-port/charts/fiat
sources:
  - https://hub.docker.com/r/nogui/crypto-port-backend-fiat
maintainers:
  - name: nougui
    email: helmcharts@nougui.net