apiVersion: v2
description: Crypto Port Benqi Helm chart for Kubernetes
name: benqi
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.16.0-0"
keywords:
  - crypto-port
  - crypto-port-benqi
  - benqi
home: https://github.com/Zekihan/helmcharts/tree/main/crypto-port/charts/benqi
sources:
  - https://hub.docker.com/r/nogui/crypto-port-backend-benqi
maintainers:
  - name: nougui
    email: helmcharts@nougui.net