{{- if .Values.secrets.values }}
{{- $fullName := include "code-server.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default $fullName }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.secrets.values }}
  {{ .name }}: "{{ .value }}"
  {{- end }}
{{- end }}