apiVersion: v2
description: Paperless Ngx Helm chart for Kubernetes
name: paperless-ngx
type: application
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless-ngx
  - paperless
home: https://github.com/Zekihan/helmcharts/tree/main/paperless-ngx
maintainers:
  - name: nougui
    email: helmcharts@nougui.net
dependencies:
  - name: postgresql
    version: 11.6.2
    repository: https://charts.bitnami.com/bitnami