apiVersion: v2
description: Cryptoprice Helm chart for Kubernetes
name: cryptoprice
type: application
version: 0.1.9
kubeVersion: ">=1.16.0-0"
keywords:
  - cryptoprice
home: https://github.com/Zekihan/helmcharts/tree/main/cryptoprice
maintainers:
  - name: nougui
    email: helmcharts@nougui.net
