{{- if .Values.secrets }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
stringData:
  {{- range .values }}
    {{ .name }}: "{{ .value }}"
  {{- end }}
---
{{- end }}
{{- end }}