{{- if .Values.telegramIngress.tls }}
{{- range .Values.telegramIngress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .crt }}
  tls.key: {{ .key }}
{{- end }}
{{- end }}