kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.s3Secret.name }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3Secret.AWS_ACCESS_KEY_ID }}
  AWS_ENDPOINTS: {{ .Values.s3Secret.AWS_ENDPOINTS }}
  AWS_REGION: {{ .Values.s3Secret.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Secret.AWS_SECRET_ACCESS_KEY }}
type: Opaque
