{{- $labels := include "paperless-ngx.labels" . | nindent 4 -}}
{{- if .Values.secrets }}
{{ range .Values.secrets }}
{{- if .name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- $labels }}
type: Opaque
stringData:
  {{- range .values }}
  {{ .name }}: "{{ .value }}"
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}