apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "puzzleswap.fullname" . }}
  labels:
    {{- include "puzzleswap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "puzzleswap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "puzzleswap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "puzzleswap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.internalPort | default 80 }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.internalPort | default 80 }}"
            - name: ENVIRONMENT
              value: 'production'
            - name: NODE_ENV
              value: 'production'
          {{- if .Values.secrets }}
            {{- range .Values.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom }}
                  key: {{ .valueFromName | default .name }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /alive
              scheme: HTTP
              port: {{ .Values.internalPort | default 80 }}
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              scheme: HTTP
              port: {{ .Values.internalPort | default 80 }}
            initialDelaySeconds: 15
            timeoutSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
