apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "adguard.fullname" . }}-config"
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  AdGuardHome.yaml:
    {{- toYaml . | nindent 4 }}
  {{- end }}