{{- if .Values.persistence.data -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "adguard.fullname" . }}-data"
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.data.size | default "100Mi" }}"
{{- end }}