apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-ingress.fullname" . }}
  labels:
    {{- include "external-ingress.labels" . | nindent 4 }}
data:
  nginx.conf: {{ .Values.nginxConf }}